"use client"

import PageHeader from "@/components/custom/shared/PageHeader"
import { Wrapper } from "@/components/custom/shared/Wrapper"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useCurrentUser } from "@/lib/hooks/useCurrentUser"
import { useWeeklyPayrolls } from "@/lib/queries/usePayroll"
import { format } from "date-fns"
import { Eye, PhilippinePesoIcon } from "lucide-react"
import { useRouter } from "next/navigation"

/**
 * Employee view of their own payroll records
 */
export default function MyPayrollPage() {
  const { user_id } = useCurrentUser()
  const router = useRouter()

  const { data, isLoading } = useWeeklyPayrolls({
    filter: { employee: user_id },
    ordering: "-week_start",
  })

  const getStatusColor = (status: string) => {
    switch (status) {
      case "paid":
        return "bg-blue-100 text-blue-800 border-blue-200"
      case "approved":
        return "bg-green-100 text-green-800 border-green-200"
      case "draft":
        return "bg-gray-100 text-gray-800 border-gray-200"
      case "cancelled":
        return "bg-red-100 text-red-800 border-red-200"
      default:
        return "bg-gray-100 text-gray-800 border-gray-200"
    }
  }

  return (
    <Wrapper>
      <div className="space-y-4 md:space-y-6">
        <PageHeader
          title="My Payroll"
          description="View your payroll history and payment details"
          icon={PhilippinePesoIcon}
        />

        {isLoading ? (
          <div className="text-center py-8 text-muted-foreground">
            Loading your payroll records...
          </div>
        ) : data?.results && data.results.length > 0 ? (
          <div className="grid gap-4">
            {data.results.map((payroll) => (
              <Card
                key={payroll.id}
                className="hover:shadow-md transition-shadow"
              >
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-lg">
                      Pay Period:{" "}
                      {format(new Date(payroll.week_start), "MMM dd")} -{" "}
                      {payroll.week_end
                        ? format(new Date(payroll.week_end), "MMM dd, yyyy")
                        : ""}
                    </CardTitle>
                    <Badge className={getStatusColor(payroll.status)}>
                      {payroll.status.toUpperCase()}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                    <div>
                      <p className="text-sm text-muted-foreground">Gross Pay</p>
                      <p className="text-lg font-semibold">
                        ₱{Number(payroll.gross_pay).toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">
                        Deductions
                      </p>
                      <p className="text-lg font-semibold text-red-600">
                        ₱{Number(payroll.total_deductions).toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">Net Pay</p>
                      <p className="text-lg font-semibold text-green-600">
                        ₱{Number(payroll.net_pay).toLocaleString()}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">
                        Total Hours
                      </p>
                      <p className="text-lg font-semibold">
                        {Number(payroll.regular_hours) +
                          Number(payroll.overtime_hours)}
                        h
                      </p>
                    </div>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => router.push(`/payroll/slip/${payroll.id}`)}
                    className="w-full md:w-auto"
                  >
                    <Eye className="size-4 mr-2" />
                    View Payslip
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <Card>
            <CardContent className="py-8 text-center text-muted-foreground">
              No payroll records found. Payroll records will appear here once
              generated by management.
            </CardContent>
          </Card>
        )}
      </div>
    </Wrapper>
  )
}
